### ISSUE TITLE
Groot's backyard

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot#13]
Dr. Everitt's neighborhood - but better and up-to-date

https://github.com/acm-uiuc/groot/issues/27

**Comment by theishshah** [comment]
What is Dr. Everitt's neighborhood? If it involves writing stuff up I can hop on it

**Comment by tyler-thetyrant** [comment]
https://wiki.illinois.edu//wiki/display/HKNDEN/Home

**Comment by narendasan** [comment]
til.acm.illinois.edu
