### ISSUE TITLE
unified payment system service

### ISSUE THREAD

**Issue by theishshah** [acm-uiuc/groot#29]
System to use venmo on the site to pay for credit dues and/or other misc. fees accrued by a user

**Comment by sameetandpotatoes** [comment]
@Salil999: I hope you still aren't working on this but I'm closing this as @bcongdon got the [groot-credit-service](https://github.com/acm-uiuc/groot-credits-service) up that will hope to accomplish this.

We will be testing the credit system aspect of the service with groot-caffeine-service, which I'll be working on in the upcoming weeks. But the credit service will likely be used to handle venmo payments as well.
