### ISSUE TITLE
DISCUSSION: first time system dependency setup script

### ISSUE THREAD

**Issue by pranaygp** [acm-uiuc/groot#30]
https://github.com/acm-uiuc/groot#first-time-setup

What do you guys think about a bash script or something that would do a lot of these for you (or atleast check compatibility for instance and just say "oh, your version of node is outdated. run ... to get setup") and then, if everything is good, just print "Your system is ready to develop for groot! Happy hacking!"

This isn't high priority but I was wondering what your thoughts are on this, because the first time setup sections seems a bit overwhelming (even though, after looking at it, seems pretty straightforward)

**Comment by narendasan** [comment]
We have moved towards docker being the main platform for development and deployment. So dependency management is less of an issue. The readme might be out of date on the latest instructions. But basically you just need to install docker and docker compose and then build the app

**Comment by bcongdon** [comment]
There was an attempt at this https://github.com/acm-uiuc/groot/pull/1. I think it ended up being closed because it's kinda difficult/dangerous to do some of the setup across different platforms.

Docker was proposed to be a solution to this, and while it isn't perfect, it's currently the "fastest" way to get up-and-running with a groot dev deployment.

This is definitely an area that we should do better in, if possible

**Comment by narendasan** [comment]
https://github.com/acm-uiuc/groot#deploying-with-docker is the most recent documentation, @bcongdon  can you write a new readme that focuses just on building and working in docker? (basically throw out what we have/move it into the wiki)

**Comment by bcongdon** [comment]
Yeah, most of that is still relevant (i.e. you do need to get `repo` setup), but I can add more detailed documentation into starting up and managing docker.

**Comment by narendasan** [comment]
I think its mostly the local setup stuff that is less relevant now and can be moved out of the readme and just linked to

**Comment by pranaygp** [comment]
I agree, docker definitely seems like the way to go here. We should definitely encourage new contributors to not fear setup and give them an easy docker setup they can use :)

I'm going to close this issue since #31 now exists
