### ISSUE TITLE
Thoughts on including display

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/groot#32]
Thoughts on including display in the groot manifest? 
We can start to integrate its development more into groot's.
Then we can start looking at bugs/improvements to the system in Groot 2.0/2.5

**Comment by bcongdon** [comment]
I think that it makes sense to tie display more closely in with groot, and it'd be great to start slating some new features for it in the 2.0/2.5 dev cycles.

That being said, I don't think it needs to be included in the manifest -- it's not run on any of the prod servers, and dev work on display doesn't inherently require dev work on groot.
