### ISSUE TITLE
List of services

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot#38]
It would be good if the root `acm-uiuc/groot` repo had a list of all the services that makes up "groot" in the README

**Comment by narendasan** [comment]
We may want to consider creating something like a documentation/development site or wiki where we can host this. (Github's wiki is a bit hidden) 
/docs + markdown + jenkins may work (like TIL)

**Comment by bcongdon** [comment]
That solution sounds like it will scale better, and I think that should be considered for the 2.x milestone.

For 1.x, I'll try to get a comprehensive list in the README to have something for new devs to look at.
