### ISSUE TITLE
Service port list

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot#44]
We should compile a list of all the service ports of the various groot services

**Comment by aashishkapur** [comment]
Link here: https://github.com/acm-uiuc/groot-api-gateway#config-values
Do we want to copy them over to this repo or onto the wiki?

**Comment by bcongdon** [comment]
Ah, didn't realize that list existed. This can be closed for now, hopefully discoverability of docs will improve when we create a dedicated documentation site
