### ISSUE TITLE
Make route handlers optional

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot#59]
It would be nice if you could just write the RouteCollection for defining routes, like:
```
Route{
    "GigInfo",
    "GET",
    "/gigs/{gig_id}",
    GigInfo,
}
```

... without having to create the additional boilerplate function for handling the request:

```
func GigInfo(w http.ResponseWriter, r *http.Request) {
    proxy.GET(w, GigURL+r.URL.String(), GigFormat, "", r)
}
```

It's nice to have the possibility of extensibility with these request handlers, but it often just makes the process of registering a service with {Groot, Arbor} more tedious.

**Comment by narendasan** [comment]
That might require us digging into the routing layer and would be something we should add to arbor over groot
